#                            -*- mode: org; -*-
#
#+TITLE:     README for [[http://openfoam.org/download/source][OpenFOAM-8]]
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     22nd July 2020
#+LINK:                  http://openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2015-2020 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* [[https://openfoam.org/download/source][Download and installation instructions]]
* [[https://openfoam.org/resources][Documentation]]
* [[https://cpp.openfoam.org/v8][Source code documentation]]
* [[https://openfoam.org/dev/coding-style-guide][OpenFOAM C++ Style Guide]]
* [[https://bugs.openfoam.org][Reporting bugs in OpenFOAM]]
* [[https://openfoam.org/contact][Contacting the OpenFOAM Foundation]]

* ELAM
Adds custom variables to selected solvers interFOAM, pimpleFoam, & simpleFOAM that
computes accelration magnitude & components, strains, node number, and boudaries
denoted by integer values to represent inlets and outlets. All variables outputs 
computed automatically except NodeBC and WSC. Template files are included below.

* NodeBC Variable Template
#+BEGIN_SRC c++
/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  8
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       volScalarField;
    location    "0";
    object      NodeBC;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 0 0 0 0 0 0];

internalField   uniform -3;

boundaryField
{
    "(walls01|walls02)"
    {
	      type		fixedValue;
	      value		uniform 0;
    }
    inlet
    {
        type    fixedValue;
	    value	uniform 1;
    }
    top
    {
	    type		fixedValue;
	    value		uniform 0;
    }
    outlet
    {
    	type		fixedValue;
    	value		uniform 2;
    }
}

// ************************************************************************* //
#+END_SRC

* WSC Variable Template
#+BEGIN_SRC c++
/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  8
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       volScalarField;
    location    "0";
    object      WSC;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 0 0 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    "(walls01|walls02)"
    {
          type     fixedValue;
	        value    uniform 0;
    }
    inlet
    {
          type     fixedValue;
	        value		 uniform 0;
    }
    top01
    {
          type     fixedValue;
	        value    uniform 0;
    }
    outlet
    {
          type     fixedValue;
	        value		 uniform 0;
    }
}

// ************************************************************************* //
#+END_SRC
